### ISSUE TITLE
手机端的右侧PC页面为空白

### ISSUE THREAD

**Issue by Cathgao** [weixiansen574/HybridFileXfer#1]
电脑系统：windows 10 专业版
手机系统：hyperOS 1.0.1 Android14
手机：红米K40S
电脑端的执行文件放在ramdisk的`R:\双轨快传`下
![b36393df4d7855ffdd19da29c957a0b](https://github.com/weixiansen574/HybridFileXfer/assets/21031564/5e048328-c08d-44dc-8ed2-c4e884f4aa95)

**Comment by Cathgao** [comment]
经过测试，直接传输是可以收到文件的，文件在PC端执行文件所在盘的**根目录**下
![85aef4aec182a27e9911307f9a6db20](https://github.com/weixiansen574/HybridFileXfer/assets/21031564/5763d0f2-78e3-4840-b10c-c40e25244f43)
![image](https://github.com/weixiansen574/HybridFileXfer/assets/21031564/89bacef4-4be8-4630-b6d1-9a96346d532c)

**Comment by Cathgao** [comment]
此外，PC端的服务关闭后，`adb.exe`进程不会结束，会一直存在于后台

**Comment by wgjddn** [comment]
一样问题,我还给软件root权限了也没用.而且手机软件不能访问根目录

**Comment by weixiansen574** [comment]
> 此外，PC端的服务关闭后，`adb.exe`进程不会结束，会一直存在于后台

adb是这样的，它就会一直待在后台，但是重复运行这个软件不会开启多个adb进程

**Comment by weixiansen574** [comment]
有相同问题的都加我qq：1695339869吧，目前我修复了一个人的问题，其他人也要进行测试

**Comment by weixiansen574** [comment]
已修复
详见：https://github.com/weixiansen574/HybridFileXfer/releases/tag/v1.1

**Comment by Cathgao** [comment]
测试已无问题，感谢作者的付出
![Screenshot_2024-04-26-00-13-33-132_top.weixiansen574.hybridfilexfer.jpg](https://github.com/weixiansen574/HybridFileXfer/assets/21031564/6908e972-02e7-4a70-bd1c-2901cf047a8d)
