### ISSUE TITLE
[bug]: 列含有大量文件的目录时服务端崩溃

### ISSUE THREAD

**Issue by TranscendMa** [weixiansen574/HybridFileXfer#24]
某次，在连接完成，在打开一个具有9000+文件的目录时，安卓app上面提示服务端挂掉了，之后的做法是直接到上一级，传输整个文件夹。
能否加入一些限制，使其发现文件数量过多时停止加载并弹出消息提示，而不是让服务端挂掉？

**Comment by weixiansen574** [comment]
什么目录那么变态？可以截图看看吗？

**Comment by TranscendMa** [comment]
是截图(DCIM/Screenshots)目录
![屏幕截图 2024-05-14 194244](https://github.com/weixiansen574/HybridFileXfer/assets/121599515/70d93e74-b05c-43cc-8190-715f4925cb94)

**Comment by freemedom** [comment]
我也遇到了这个问题，一个3万文件的目录，全选传到电脑。会显示
发生异常 服务端已终止
但是到上级目录选中这个文件夹，然后传，是可以的

**Comment by weixiansen574** [comment]
靠，又是aidl传输限制的原因，这个还没有考虑到
