### ISSUE TITLE
电脑端多个adb设备能指定adb连接特定

### ISSUE THREAD

**Issue by cainiao524** [weixiansen574/HybridFileXfer#28]
学校宿舍拉跨用随身wifi用usb线连电脑，手机开热点电脑连wifi，然而随身WiFi也算adb连接。adb默认识别到2个设备直接退出。希望能加个手动选择而不是直接退出

**Comment by weixiansen574** [comment]
你看说明没？
https://github.com/weixiansen574/HybridFileXfer?tab=readme-ov-file#adb%E6%8C%87%E5%AE%9A%E8%AE%BE%E5%A4%87
