### ISSUE TITLE
在windoows上,当adb存在多个设备时无法手动指定安卓设备

### ISSUE THREAD

**Issue by crmmc** [weixiansen574/HybridFileXfer#3]
platform: 
windows 10 2022H
红木K50Ultra 安卓13 MIUI14.0.5
已root但使用为root模式

我的电脑中开着部分安卓模拟器用于游戏,当我想要测试此软件时,**默认会报错adb发现多于一个设备被发现**,这是正常情况.
但是软件似乎并没有给用户选择所使用的设备的余地

**在adb中,可使用 -s {设备代号} 来指定对某一个设备进行操作.** 

比如adb devices 表现出一个设备名称为 xxxxx1, xxxxx2 那使用 **adb -s xxxxx2 shell** 即可指定进入某个特定设备的shell .希望能在pc端的软件加入一个开关用于传入本次指定的服务端的参数,方便当电脑存在链接多个设备的情况下使用此软件

**Comment by weixiansen574** [comment]
已更新，若没问题可以关闭issues了
