### ISSUE TITLE
 【建议】增加传输完成提示

### ISSUE THREAD

**Issue by XieyilinMain** [weixiansen574/HybridFileXfer#31]

**Comment by WeLonely** [comment]
我也希望能增加该功能，虽然是参考FastCopy不计算预计耗时，但FastCopy拷贝完成后也是有完成提示的。
缺少这个提示，传输结束后没有传输速度的时候，就不确定是传输成功还是失败。

**Comment by cute-omega** [comment]
虽然但是至少现在是有完成提示的啊？（手机端也有，懒得截图了）
![image](https://github.com/user-attachments/assets/6d908a7e-dc33-4be1-a7ef-70b8f4c1ed75)

**Comment by weixiansen574** [comment]
2.0版本加了，已经改了大动脉。他这个issues是之前的版本提的
