### ISSUE TITLE
增加对SMB协议的支持

### ISSUE THREAD

**Issue by xiaoweiXX** [weixiansen574/HybridFileXfer#44]
增加对SMB协议的支持，我试过几个支持SMB的APP，不知道为啥都有奇怪的限速，最高的速度也只有20MB/S（还维持不了）。我的内网整个链路的瓶颈就是NAS上的一个千兆网口，不应该这么慢才对​。希望能支持一下SMB协议，这样哪怕还有奇怪的20MB/S的限制，多一个通道也能跑到40MB/S

**Comment by weixiansen574** [comment]
那个是NAS应用程序开发，关我屁事，我只管传文件到电脑。
但的确可以使用多网卡多连接来加速，但是SMB好像不能多线程写一个文件吧

**Comment by xiaoweiXX** [comment]
> 那个是NAS应用程序开发，关我屁事，我只管电脑与手机的文件互传。（要做就是另一个APP了🤓）
> 但的确可以使用多网卡多连接来加速，但是SMB好像不能多线程写一个文件吧

主要是我移动端用别的APP都会有这个奇怪的限速，前两天试了试评论区的cx文件管理器也只能跑到三百兆，但是Windows不用特殊设置就能跑到千兆，所以我在想是不是那些APP都有问题（因为那些一个APP一个速度，像是APP有各自的问题）。看到你这个项目，想问一下能不能支持一下SMB跑到链路的极限，哪怕是单线程对比我找的这几个APP也有很大的提升了。（不做NAS端的应用或者做个docker也行）
另外我不清楚SMB能不能多线程写一个文件，但是可以多线程写多个文件。SMB在写每个文件的时候是有最低时间的，如果写大量的小文件那每秒只能写入不超过5个文件。微软官方的文档说Windows自带文件管理不支持SMB多线程功能，可以自己找一个支持多线程的应用写入（我用安卓端APP写入也有这个现象）。但是我用FreeFilesync同步文件，把线程开到上万个也没什么提升，我在想是不是这个应用有什么问题（还是说我把NAS用SMB协议挂载成网络硬盘，FreeFilesync传输文件的时候实际上走的是Windows文件管理的渠道）。如果作者也能开发一个支持SMB多线程的Windows端应用就好了。
