### ISSUE TITLE
[建议]做一个包含java整合包,这样软件可以放到U盘里面随插随用了

### ISSUE THREAD

**Issue by swodni** [weixiansen574/HybridFileXfer#51]
好多人不知道如何建立java环境,经过我测试,电脑可以不安装java,只把安装java之后那些文件都复制出来也可以运行你的软件.只要把你的软件所有文件放到java文件夹里的bin文件夹里就可以直接运行.
所以我建议你可以做一个包含java整合包发到release里.这样的话你这个软件就可以放到U盘里面随插随用了.

**Comment by f59375543** [comment]
> > 可以自行想办法整合吗，这个功能我很需要，求问如何内置
> 
> 我已经做好了，顺便写了个基于C的启动器，不过我不知道作者介意合并一个JDK进去吗

可以先做一个分支吧

**Comment by Oldcucumber** [comment]
> > > 可以自行想办法整合吗，这个功能我很需要，求问如何内置
> > 
> > 
> > 我已经做好了，顺便写了个基于C的启动器，不过我不知道作者介意合并一个JDK进去吗
> 
> 可以先做一个分支吧

已经叉了，并且提交了pr，作者暂时没有合并，你可以去pr源下
