### ISSUE TITLE
在朋友的鸿蒙4.0上面给予了权限读不出目录

### ISSUE THREAD

**Issue by long45343** [weixiansen574/HybridFileXfer#52]
左边一片空白，点按返回键提示已经是根目录了

**Comment by XZH2024** [comment]
MIUI12.5同样有这个问题

https://github.com/user-attachments/assets/72b3e680-39f8-4a0b-847c-63257ff56a55

![Screenshot_2024-11-09-12-06-20-630_com miui securitycenter](https://github.com/user-attachments/assets/b1dc2744-28d6-4739-b65d-9429800ca069)

**Comment by weixiansen574** [comment]
所有文件访问权限？

**Comment by XZH2024** [comment]
应该是有所有文件访问的权限的，使用root模式后可以正常访问，标准模式还不行
![Screenshot_2024-11-09-12-39-10-711_com miui securitycenter](https://github.com/user-attachments/assets/cf5106b3-5345-4315-b579-a5d90aedf904)

**Comment by weixiansen574** [comment]
你安卓几啊？

**Comment by XZH2024** [comment]
10

**Comment by weixiansen574** [comment]
要不远程调试😁

**Comment by XZH2024** [comment]
算了吧.....我这边使用Root模式还是可以正常使用的......
另外还有个小问题，就是每次打开都得重新设置连接模式和连接方式，要是能记住上次选择就好了

**Comment by weixiansen574** [comment]
我也挺烦的，马上改

**Comment by peasoft** [comment]
ColorOS 7 (Android 10) 同样存在问题。
