### ISSUE TITLE
【建议】建议增加 adb 轨道多系统支持（linux、macos）

### ISSUE THREAD

**Issue by awsl1414** [weixiansen574/HybridFileXfer#57]
经测试，wifi轨道支持多系统，但是adb不支持linux和macos

【方案1】
判断环境变量里是否有 adb ，优先使用环境变量 adb
【方案2】不推荐
增加对应平台的 adb 二进制文件，目前仅有windows平台的，linux 和 macos 需要补充

**Comment by Oldcucumber** [comment]
[https://github.com/weixiansen574/HybridFileXfer/pull/61](url)
已提交Pr
