### ISSUE TITLE
以已获取root权限，但无法访问根目录

### ISSUE THREAD

**Issue by ckstc** [weixiansen574/HybridFileXfer#58]
如图

![Screenshot_2024-12-13-09-47-13-672_top.weixiansen574.hybridfilexfer.jpg](https://github.com/user-attachments/assets/943dd96a-b316-44ae-8370-ad875e30c4b8)

![Screenshot_2024-12-13-09-47-19-120_top.weixiansen574.hybridfilexfer.jpg](https://github.com/user-attachments/assets/3fcf6d85-d131-4931-aa2a-96192f4a3206)

**Comment by weixiansen574** [comment]
自己cd到根目录，右上角，跳转目录：`/`
