### ISSUE TITLE
Error: Unable to access jarfile HybridFileXfer.jar

### ISSUE THREAD

**Issue by XZH2024** [weixiansen574/HybridFileXfer#59]
脚本里面的程序名字是HybridFileXfer.jar
但是实际存在的文件名为HybridFileXfer-PC.jar
导致了这个错误
直接把HybridFileXfer-PC.jar的-PC去掉或者在启动脚本里面补全文件名就可以了
![image](https://github.com/user-attachments/assets/7ce6dfbd-8692-499e-a0a5-7d252e7fe272)
![image](https://github.com/user-attachments/assets/6af99229-7bfe-4d5c-9289-0a66da6a9489)
![image](https://github.com/user-attachments/assets/e1787c48-7a5c-431d-a302-f1b4d9fbcb61)

**Comment by weixiansen574** [comment]
多谢提醒！release已改
