### ISSUE TITLE
关于新增的PC快捷启动器

### ISSUE THREAD

**Issue by Reweng** [weixiansen574/HybridFileXfer#60]
本人 PC 已经配置好环境 jdk 了。快捷启动器打开就自动下载 jdk ……
建议加一个判断环境变量里是否有 jdk ，优先使用环境变量 jdk，没有再决定是否下载 jdk ，由启动器下载 jdk 或者自行下载配置

**Comment by Oldcucumber** [comment]
我是快捷启动器编写者，感觉这样判断怪麻烦的，还不确定你的jdk版本兼容与否，而且设计理念实际上是能打包到移动设备里面Run  Anywhere，你要是有这个需求可以手动改一下start.c自己编译一个版本，或者手动写个启动的cmd就行

**Comment by Reweng** [comment]
> 我是快捷启动器编写者，感觉这样判断怪麻烦的，还不确定你的jdk版本兼容与否，而且设计理念实际上是能打包到移动设备里面Run Anywhere，你要是有这个需求可以手动改一下start.c自己编译一个版本，或者手动写个启动的cmd就行

判断确实是个问题。
