### ISSUE TITLE
在手机上将软件切到后台之后十几秒再切回来,传输速度显示会短暂出现bug

### ISSUE THREAD

**Issue by wad-sad** [weixiansen574/HybridFileXfer#62]
我是iqoo7橘子4系统,软件用的root模式,bug如图
![Image](https://github.com/user-attachments/assets/a8ea942b-1826-482e-b445-64b59cacd095)

**Comment by weixiansen574** [comment]
然后速度会变回正常吗?

**Comment by wad-sad** [comment]
会，只是速度显示出bug，后台切回来后很快就恢复了，实际上传输速度并未变化

**Comment by weixiansen574** [comment]
这样啊，那这个bug无害，不用管他。不过，还是建议放在前台，不然会出现很多问题。
